version: '3.8'

services:
  test_app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - test_postgres
    env_file:
      - .env
    environment:
      - DB_HOST=${TEST_DB_HOST}
      - DB_PORT=${TEST_DB_PORT}
      - DB_NAME=${TEST_DB_NAME}
      - DB_USER=${TEST_DB_USER}
      - DB_PASS=${TEST_DB_PASS}
      - RUN_TESTS=True

  test_postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
    volumes:
      - test_pg_data:/var/lib/postgresql/data


volumes:
  test_pg_data:
