version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    volumes:
      - app_static:/app/src/staticfiles
      - app_media:/app/src/media
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - app_static:/app/static
      - app_media:/app/media
    ports:
      - ${ROOT_PORT}:8080
    depends_on:
      - app
    restart: always


volumes:
  pg_data:
  app_media:
  app_static:
